# Generated by Django 4.0.5 on 2022-06-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documentos/')),
                ('privada', models.TextField()),
                ('password', models.TextField()),
                ('certificado', models.FileField(upload_to='certificados/')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verificar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.TextField()),
                ('documento', models.FileField(upload_to='documentos/')),
                ('certificado', models.FileField(upload_to='certificados/')),
            ],
        ),
        migrations.CreateModel(
            name='Llaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publica', models.TextField()),
                ('privada', models.TextField()),
                ('password', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.persona')),
            ],
        ),
    ]
