# Generated by Django 4.0.5 on 2022-06-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Llaves',
            new_name='Llave',
        ),
        migrations.RenameModel(
            old_name='Verificar',
            new_name='Valido',
        ),
    ]
