# Generated by Django 4.0.5 on 2022-06-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0002_rename_llaves_llave_rename_verificar_valido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='password',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='privada',
            new_name='pais',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='certificado',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='documento',
        ),
        migrations.AddField(
            model_name='firma',
            name='ciudad',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='firma',
            name='correo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='firma',
            name='departamento',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='firma',
            name='estado',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='firma',
            name='organizacion',
            field=models.TextField(default=''),
        ),
    ]
