# Generated by Django 4.0.5 on 2022-06-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0003_rename_password_firma_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
                ('documento', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='llave',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
