# Generated by Django 4.0.5 on 2022-06-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0004_integridad_remove_llave_persona_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='contrasena',
            field=models.TextField(default=''),
        ),
    ]
